repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: ^(cfn/|onpoint_nested_cfn/)
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.86.2
    hooks:
      - id: cfn-lint
        files: ^cfn/.*\.ya?ml$
